site_name: "Iris Toolbox Reference Manual"

theme:
    name: material
    font: 
        code: "PT Mono"
        text: "Montserrat"
    icon: 
        logo: octicons/book-24
        repo: fontawesome/brands/github
    favicon: "images/book-open-blank-variant.ico?9"
    palette:
        scheme: default
        primary: blue grey
    features:
        - navigation.tabs
        - navigation.indexes
    custom_dir: overrides

repo_url: https://github.com/IRIS-Solutions-Team/iris-reference
repo_name: iris-reference
edit_uri: ""

extra_css:
  - stylesheets/extra.css

extra:
  version: 2021

use_directory_urls: false
docs_dir: source
site_dir: docs

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.critic
    - pymdownx.highlight
    - pymdownx.superfences
    - footnotes
    - meta
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - javascripts/mathjax-config.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - awesome-pages


