name: Build on push to iris-toolbox

on:
  repository_dispatch:
    types: [iris-toolbox-push-bleeding]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: IRIS-Solutions-Team/IRIS-Toolbox
          token: ${{ secrets.IRIS_TOOLBOX_TOKEN }}
          ref: bleeding
          path: ./iris-toolbox
      - name: Echo
        run: ls ./iris-toolbox

        
